from products.views.products import ProductListView
from products.views.products import ProductDetailView
from products.views.products import category_add_view
from products.views.products import product_add_view
from products.views.products import product_edit_view
from products.views.products import product_delete_view
from products.views.categories import categories_view
from products.views.categories import category_edit_view
from products.views.categories import category_delete_view
from products.views.categories import category_products_view